load("~/Downloads/.RData")
table <-read.csv("Sample project in R - Sheet1(1).csv" ,TRUE , ",")
setwd("~/Downloads")
table <-read.csv("Sample project in R - Sheet1(1).csv" ,TRUE , ",")
table <- read.csv("Sample project in R - Sheet1(1).csv" , TRUE , ",")
table <- read.csv("ExcelR.csv" , TRUE , ",")
plot(table$Name , table$Account.Balance.in..Millions., ylab="Name" , xlab="Account.Balance.in..Millions.")
plot(table$Name , table$Account.Balance.in..Millions., xlab="Name" , ylab="Account.Balance.in..Millions.")
View(table)
plot(table$Name , table$Rate.of.interest.in.savings.account, xlab="Name" , ylab="Rate.of.interest.in.savings.account")
plot(table$Name , table$Interest.earned.for.1.year, xlab="Name" , ylab="Interest.earned.for.1.year")
plot(table$Name , table$Total.for.1.years, xlab="Name" , ylab="Total.for.1.years")
plot(table$Name , table$Total.for.10.years, xlab="Name" , ylab="Total.for.10.years")